version: "3"
services:
  appdb:
    image: postgres:13
    container_name: "prismadb"
    env_file:
      - ../.env.local
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: hogehoge
      MINIO_SECRET_KEY: fugafuga
    command: server /data
    volumes:
      - "s3-data:/data"
    ports:
      - "9090:9000"
volumes:
  s3-data:
  database:
    driver: local
