name: Test
on: [pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # ref: https://github.com/actions/setup-node#v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      # ref: https://github.com/reviewdog/reviewdog#github-action-reviewdogaction-setup
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      # ref: https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      # ref: https://github.com/reviewdog/reviewdog#available-pre-defined-errorformat
      - name: Typecheck
        run: yarn tsc | reviewdog -f=typescript -reporter=github-pr-review
        with:
          github_token: ${{ secrets.github_token }}
      # ref: https://github.com/reviewdog/action-eslint#githubworkflowsreviewdogyml
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: "./**/*.{ts,tsx,mdx}"
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: yarn build
